### ISSUE TITLE
[Bug] After mod installation, Loading my saved creations does not work.

### ISSUE THREAD

**Issue by Sidthefridge** [christheboss894/PPG2-Electric-Boogaloo#10]
**Describe the bug**
The inability to load saved creations after mod installation.

**To Reproduce**
Steps to reproduce the behaviour:
1. install mod
2. load into a game
3. try to load something in
4. doesn't work

**Expected behaviour**
It should work

**Screenshots**
N/A

**Additional context**
I have no idea if its like this for others.

**Comment by christheboss894** [comment]
Unfortunately this cannot be fixed, as i have no clue what is causing it. saving will still work though.

**Comment by TumbleBee6** [comment]
I'm having the same problem.
