### ISSUE TITLE
when i open my people playground 1.2.7 i put the mod and texture pack properly then after a few minutes or so the game crashes and i tried doing the mod without texture and after and i restarted my pc it just shows the logo of unity AND it crashes.[Bug]

### ISSUE THREAD

**Issue by peepeepeanut** [christheboss894/PPG2-Electric-Boogaloo#11]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:
1. Spawn in
2. Stab
3. Fling

**Expected behaviour**

**Screenshots**

**Additional context**

**Comment by peepeepeanut** [comment]
[![image](https://user-images.githubusercontent.com/60063154/72680081-b3b88d80-3af0-11ea-9b13-2b589d963e90.png)
](url)

**Comment by peepeepeanut** [comment]
[![image](https://user-images.githubusercontent.com/60063154/72680088-cd59d500-3af0-11ea-9ab6-a711e9306dbb.png)
](url)

**Comment by peepeepeanut** [comment]
[![image](https://user-images.githubusercontent.com/60063154/72680092-df3b7800-3af0-11ea-94af-3e27f229ec82.png)
](url)

**Comment by peepeepeanut** [comment]
after that it crashes.

**Comment by christheboss894** [comment]
are you pirating the game? @peepeepeanut

**Comment by peepeepeanut** [comment]
> are you pirating the game? @peepeepeanut

yeah...

**Comment by christheboss894** [comment]
thats your problem

**Comment by peepeepeanut** [comment]
ok how di fix it?

**Comment by peepeepeanut** [comment]
do*

**Comment by christheboss894** [comment]
by not pirating the game

**Comment by peepeepeanut** [comment]
how?

**Comment by christheboss894** [comment]
by not pirating

**Comment by peepeepeanut** [comment]
ok fine -_-
