### ISSUE TITLE
[Bug] saves

### ISSUE THREAD

**Issue by plushfoxy109** [christheboss894/PPG2-Electric-Boogaloo#12]
**Description**
Whenever I load into people playground and use this mod I cant load my saves.

**To Reproduce**
1. Start game
2. Go to saves
3. Try to spawn in save
4. Wont load

**Additional context**
Is there a way I can make a copy of people playground and use the mod in that to make stuff?

**Comment by christheboss894** [comment]
unfortunately, as I don't know why this problem occurs, I cannot fix it. don't worry though it will be fixed in 1.2.8 mod release and you can still save items, but loading them won't work.
