### ISSUE TITLE
[Bug] Game crash instantly after trying to play a map

### ISSUE THREAD

**Issue by Looopering** [christheboss894/PPG2-Electric-Boogaloo#13]
**Describe the bug**
When I try to launch a map, the game instantly crashes with giving some kind of error box from unity.

**To Reproduce**
1. Open the game
2. Choose a map
3. Crash
**Expected behaviour**
The map would load, and I'll would think that i could play the game?

**Screenshots**
![crashj](https://user-images.githubusercontent.com/51138696/74085365-97b56580-4a78-11ea-9126-4488aa5228de.PNG)

**Additional context**

**Comment by christheboss894** [comment]
r u pirating the game?

**Comment by Looopering** [comment]
No of course not, here my profile for proof: https://steamcommunity.com/id/Loopering/

**Comment by christheboss894** [comment]
are you on 1.2.9?

**Comment by Looopering** [comment]
How can i see on which version it is?

**Comment by christheboss894** [comment]
on ur steam, r u on beta?

**Comment by Looopering** [comment]
No I'm on the normal version

**Comment by christheboss894** [comment]
idk then
