### ISSUE TITLE
The text on the screen is not showing up.

### ISSUE THREAD

**Issue by StuartLittle21** [christheboss894/PPG2-Electric-Boogaloo#14]
When I followed the steps exactly, the text on the screen of people playground doesn't show up.

**To Reproduce**
1. Download the resource pack and Assembly-C sharp.
2. Put the resource pack in people playground-data, and the Assembly-C sharp in managed.
3. Replace both of them.
4. When I started up the game, the letters are not there, and I can't click on anything.

**Expected behavior**
I thought the game was going to be fine.

**Screenshots**

**Additional context**

**Comment by christheboss894** [comment]
the last change was 5 months ago, if you want the mod to be updated then go on the discord where it already is

**Comment by StuartLittle21** [comment]
Thank you for helping me?
