### ISSUE TITLE
only the background of the menu appears other than the notifications of the mods

### ISSUE THREAD

**Issue by yeaidklol** [christheboss894/PPG2-Electric-Boogaloo#15]
**Describe the bug**
when i open people playground (which i had to rename people playground and the data folder to "peple plpyground" to get past microsoft family features) it opens correctly and it shows the notifications for the other mods i have being enabled but none of the menu text appears, i am using version 1.20 which is the latest update,

**To Reproduce**
i open "peple plpyground"
it loads
it shows the notifications
nothing,
i click around where the text would be to see if it is as simple as it not appearing
nothing happens.

**Expected behaviour**
i open "peple plpyground"
it shows the mod notifications
the menu text is there
i click on it
and play modded people playground

**Screenshots**
![image](https://user-images.githubusercontent.com/88514658/128427112-95ed29b4-0573-4843-8c8c-11ade534482b.png)

**Additional context**
this bug is how i found out that the camera for the menu background is slowlydescending

Please help

**Comment by christheboss894** [comment]
1. The mod is no longer supported.
2. Renaming any folders will break the game, with or without mods, they must remain their original names
