### ISSUE TITLE
Mod does not work.

### ISSUE THREAD

**Issue by StatiK404** [christheboss894/PPG2-Electric-Boogaloo#16]
Assets in main PeoplePlayground_Data

Dll. in Managed

Clicking play on steam. A window shows up and dissapears afterwards.
5 Seconds later the stop button on steam turn to the play button again.
CANNOT PLAY THE GAME PROPERLY

**Comment by christheboss894** [comment]
The mod is no longer supported

**Comment by christheboss894** [comment]
To fix the game, right click on People Playground in your steam library, click properties, click local files and then click Verify integrity of game files..

**Comment by StatiK404** [comment]
> To fix the game, right click on People Playground in your steam library, click properties, click local files and then click Verify integrity of game files..

that just reverts it to the normal game i want to play modded but the game doesnt open

**Comment by StatiK404** [comment]
> The mod is no longer supported

is there still a way to play it though?

**Comment by christheboss894** [comment]
No, you must install normal workshop mods, the mod was discontinued after workshop support came out.
