### ISSUE TITLE
How do I toggle the extra syringes?

### ISSUE THREAD

**Issue by TumbleBee6** [christheboss894/PPG2-Electric-Boogaloo#9]
Title.

**Comment by christheboss894** [comment]
they will be listed as the death syringe, the description will have the buttons

**Comment by TumbleBee6** [comment]
And how do I use the multi syringe?

**Comment by christheboss894** [comment]
by pressing the numbers equivalent to the specified syringe

**Comment by TumbleBee6** [comment]
Thanks.
